# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]

    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: tr3t0r!
          MYSQL_DATABASE: tretori-test
          MYSQL_USER: tretori-user
          MYSQL_PASSWORD: tr3t0r!
        ports:
          - 3307:3306

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build project
        run: yarn build
      # - name: Migrate
      # run: knex migrate:latest

      - name: Test - unit tests
        run: yarn test

      - name: Test - e2e tests
        run: yarn test:e2e
